apiVersion: apps/v1
kind: Deployment
metadata:
  name: stun-client
spec:
  selector:
    matchLabels:
      app: stun-client
  replicas: 5
  template:
    metadata:
      labels:
        app: stun-client
    spec:
      containers:
      - name: stun-client
        image: ahovgaard/stun-client:0.1.12
        imagePullPolicy: Always
        env:
        - name: STUN_SERVER_IP
          value: "13.70.200.12"
        - name: STUN_SERVER_PORT
          value: "3478"
        - name: STUN_CLIENT_COUNT
          value: "1000"
        - name: LOG_LEVEL
          value: "warning"
        resources:
          limits:
            cpu: "2.00"
            memory: "2048Mi"
          requests:
            cpu: "2.00"
            memory: "2048Mi"
        readinessProbe:
          exec:
            command:
            - /bin/true
        livenessProbe:
          exec:
            command:
            - /bin/true
      securityContext:
        runAsUser: 1000
