apiVersion: apps/v1
kind: Deployment
metadata:
  name: stun-server
spec:
  selector:
    matchLabels:
      app: stun-server
  replicas: 2
  template:
    metadata:
      labels:
        app: stun-server
    spec:
      containers:
      - name: stun-server
        image: ahovgaard/stun-server:0.1.4
        imagePullPolicy: Always
        env:
        - name: LOG_LEVEL
          value: "info"
        resources:
          limits:
            cpu: "2.00"
            memory: "512Mi"
          requests:
            cpu: "2.00"
            memory: "512Mi"
